### ISSUE TITLE
Samsung browser activates pull to refresh

### ISSUE THREAD

**Issue by JudeOsborn** [glomotion/gesture-helper#13]
For some reason Samsung's (annoying) browser does a pull to refresh on swiping down. Chrome does not.

To make it stop I would usually use preventDefault (with passive: false), but it's not clear to me why Chrome and Safari seem to work fine. It's only the Samsung browser that appears to be a problem.

**Comment by glomotion** [comment]
Heya Jude! :)

OK, so modern browsers can actually have that feature disabled by putting the style below onto the element that scrolls:
```
.something {
  /* Disables pull-to-refresh but allows overscroll glow effects. */
  overscroll-behavior-y: contain;
}
```
The Samsung browser might not yet be able to use that style code tho - so......

One other thing to check/try (i'm pretty sure i've run into this kind of thing before) - is do the sourceEvent.preventDefault() thing - but do it before gesture-helper has properly recognised the pan/swipe gesture (sometimes takes the touch-move event firing once or twice before this happens - which is too late to prevent default browser behaviour). For this purpose - you can try listening for the "pan.prestart" event. 

let me know how you go!

**Comment by JudeOsborn** [comment]
Already tried both of those unfortunately. They work fine for all browsers except Samsung. I'm thinking something is up with the Samsung browser. If so, no big surprise there.

**Comment by JudeOsborn** [comment]
Yes, happening on the. fairly recent and updated S8. I'll give those a try.
Thanks for the help.

**Comment by glomotion** [comment]
Hey @JudeOsborn - is this still a problem? Or did you manage to fix the issue with an update or some other work around?

**Comment by JudeOsborn** [comment]
I don't remember actually. Pretty sure I wasn't able to fix it but we're
not really worried about it at this point. :)

**Comment by glomotion** [comment]
hehe Okie dokie. I might close this issue out then. I guess samsung's gon be samsung... :P
